name: PyInstaller (Windows)

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'MIDI Middleware.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: '__name__'
